### Запрос на создаие студента
POST http://localhost:8080/create_student?first_name=Grisha&last_name=Yuriev&date_of_birth=07.05.1998

### Запрос на получение ID студента
GET http://localhost:8080/get_id_student?first_name=Oleg&last_name=Sergeyev&date_of_birth=31.01.1999

### Запрос на удаление студента по ID
DELETE http://localhost:8080/delete_student?id=3

### Запрос на поиск студента по ID
GET http://localhost:8080/get_students_info_by_id?id=3

### Запрос на поиск студента по имени
GET http://localhost:8080/get_students_info_by_name?first_name=Oleg&last_name=Sergeyev

### Запрос на создание комнаты
POST http://localhost:8080/create_room?room_number=11A&number_of_beds=4

### Запрос на удаление комнаты по номеру
DELETE http://localhost:8080/delete_room?room_number=11D

### Запрос на заселение студента в комнату
POST http://localhost:8080/add_to_room?room_number=11A&student_id=1

### Запрос на выселение студента из комнаты
POST http://localhost:8080/remove_from_room?student_id=2&room_id=11A

### Запрос на получение данных жильцов комнаты по номеру
GET http://localhost:8080/get_students_room?room_number=11A

### Запрос на получение данных о комнате по номеру
GET http://localhost:8080/get_room_info?room_number=11A

### Запрос на создание группы
POST http://localhost:8080/create_group?group_id=MTiT-3&course=3&number_of_places=27&specialization=Information+Technology

### Запрос на удаление группы
DELETE http://localhost:8080/delete_group?group_id=MTT-7

### Запрос на добавление студента в группу  ?????
POST http://localhost:8080/add_to_group

### Запрос на удаление студента из группы   ?????
POST http://localhost:8080/remove_from_group

### Запрос на получени данных студентов группы   ?????
POST http://localhost:8080/get_students_group

### Запрос на получение данных о группе по ID   ?????
GET http://localhost:8080/get_group_info
